name: Python 3.12 Linting

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install linters
        run: |
          pip install black flake8

      - name: Run Black formatting check
        run: black src/ tests/ --check --verbose

      - name: Run Flake8 linting
        run: flake8 src/ tests/ --count --show-source --statistics